apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-pvc-files
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  volumeName: "redmine-pv-files"
