apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-pv-files
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.101.192
    path: "/srv/redmine-files"
