apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-pvc-plugins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  volumeName: "redmine-pv-plugins"
